### ISSUE TITLE
ipad support (or clarify documentation)

### ISSUE THREAD

**Issue by brysonjonesy** [mobile-dev-inc/action-maestro-cloud#7]
We set up a few flows and didn't realize it was a phone size screen until the maestro-cloud test ran. none of the documentation says that iOS tests run on phones only.

**Comment by igorsmotto** [comment]
Hey @brysonjonesy! 

Since this repository is only about the Maestro Cloud Github Action and your issue is not related to it. I'm gonna close this issue. However, my suggestion is to send this issue to the [official Maestro repository](https://github.com/mobile-dev-inc/maestro/issues) or the [Slack channel](https://docsend.com/view/3r2sf8fvvcjxvbtk)
